# Generated by Django 4.2.20 on 2025-03-06 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('accountNumber', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tripTitle', models.CharField(max_length=255)),
                ('pickup', models.CharField(max_length=150, unique=True)),
                ('dropoff', models.CharField(max_length=150, null=True)),
                ('cycleUsed', models.CharField(unique=True)),
                ('instructions', models.TextField(blank=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tripNumber', models.PositiveIntegerField(blank=True, null=True)),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currentLocation', models.CharField(max_length=255)),
                ('pickup', models.CharField(max_length=150, unique=True)),
                ('dropoff', models.CharField(max_length=150, null=True)),
                ('currentCycleUsed', models.CharField(unique=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('logNumber', models.PositiveIntegerField(blank=True, null=True)),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trip')),
            ],
        ),
    ]
