# Generated by Django 4.2.20 on 2025-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='currentCycleUsed',
            field=models.CharField(),
        ),
    ]
