# Generated by Django 4.2.20 on 2025-03-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logsheet_currentcycleused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='tripId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logSheets', to='core.trip'),
        ),
    ]
