# Generated by Django 4.2.20 on 2025-03-10 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logsheet_tripid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='BjxI9WRpB1rEIs4ZBTMTeVy1XEAcUGZZqFQGmPU2sknt74zrkQ2Gb7m8z2EDzwAl', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='core.driver')),
            ],
            options={
                'unique_together': {('driver', 'token')},
            },
        ),
    ]
