# Generated by Django 4.2.20 on 2025-03-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_refreshtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
